en:
  - What should you do today to make someone else happy?
  - What am I grateful for?
  - What do I want to learn today?
  - Whom would I most like to look over the shoulder?
  - What books are you reading?
  - What books should I be reading?
  - Try anything new lately?
  - Anything inspire you lately?
  - Seen any great design recently?
  - What did you do this weekend?
  - What am I going to do differently today?
  - What - realistic - dream is on your wishlist?
  - What do you want to do for the first time in your life?
  - Which exciting things, that are challenging for you, will you be doing in the next days?
  - Which decisions can you make today to make tomorrow a better day?
  - Name 3 moments/experiences from the past few days for which you are grateful
  - Failing to plan is planning to fail;<br/>So what could make tomorrow a great day?
de:
  - Was solltest du heute tun, um jemand anderen glücklich zu machen?
  - Wofür bin ich dankbar?
  - Was möchte ich heute lernen?
  - Wem würde ich am liebsten über die Schulter schauen?
  - Welche Bücher lest du?
  - Welche Bücher sollte ich lesen?
  - Hast du in letzter Zeit etwas Neues ausprobiert?
  - Hat dich in letzter Zeit etwas inspiriert?
  - Hast du in letzter Zeit ein tolles Design gesehen?
  - Was hast du am Wochenende gemacht?
  - Was werde ich heute anders machen?
  - Welcher - realistische - Traum steht auf deine Wunschliste?
  - Was willst du zum ersten Mal in deinem Leben tun?
  - Welche aufregenden Dinge, die dich herausfordern, werdest du in den nächsten Tagen tun?
  - Welche Entscheidungen kannst du heute treffen, um morgen zu einen besseren Tag zu machen?
  - Nenne 3 Momente/Erlebnisse aus den letzten Tagen, für die du dankbar bist
  - Wer nicht plant, plant zu scheitern;<br/>Wie also könnte morgen ein großer Tag werden?
nl:
  - Wat moet je vandaag doen om iemand anders gelukkig te maken?
  - Waar ben ik dankbaar voor?
  - Wat wil ik vandaag leren?
  - Wie zou ik het liefst over de schouder kijken?
  - Welke boeken lees je?
  - Welke boeken zou ik moeten lezen?
  - Probeer je iets nieuws de laatste tijd?
  - Iets wat je de laatste tijd inspireert?
  - Heb je onlangs nog iets moois gezien?
  - Wat heb je dit weekend gedaan?
  - Wat ga ik vandaag anders doen?
  - Welke - realistische - droom staat er nog op je verlanglijstje?
  - Wat wil je voor het eerst in je leven doen?
  - Welke spannende dingen, die voor jou uitdagend zijn, ga je de komende dagen doen?
  - Welke beslissingen kun je vandaag nemen om morgen tot een betere dag te maken?
  - Noem 3 momenten/ervaringen van de afgelopen dagen waarvoor je dankbaar bent
  - Niet plannen is plannen om te mislukken;<br/>Dus wat kan van morgen een mooie dag maken?
fr:
  - je ne parlez pas Français
jp:
  - Watashi wa nihon-go ga hanesemasen